### ISSUE TITLE
 No module named 'artemis.ml.tools.running_averages

### ISSUE THREAD

**Issue by jiwoongim** [petered/uoro-demo#1]
Hi. I get the following error when I try to run the demo.=

```
(Pytorch) [ji641@lion13 uoro_demo]$ pip install -e git+http://github.com/QUVA-Lab/artemis.git#egg=artemis
(Pytorch) [ji641@lion13 uoro_demo]$ python demo_uoro_anbn.py 
Traceback (most recent call last):
  File "demo_uoro_anbn.py", line 14, in <module>
    from uoro_demo.online_experiment_helpers import plot_learning_curve, \
  File "/home/ji641/projects/uoro-demo/uoro_demo/online_experiment_helpers.py", line 7, in <module>
    from artemis.ml.tools.running_averages import RunningAverage, RecentRunningAverage
ModuleNotFoundError: No module named 'artemis.ml.tools.running_averages'
```

Which version of artemis should I use?

**Actually, is this Python 3 compatible or only for python 2.7?**

Thanks

**Comment by petered** [comment]
Ah sorry about that, you can get artemis here: https://github.com/petered/artemis .  All should be Python 3 compatible

**Comment by jiwoongim** [comment]
Thanks for the reply!

Your pip install artemis doesn't give the latest version. 
For example, 
```
(Pytorch) [ji641@lion1 uoro_demo]$ python
>>> import artemis
>>> import artemis.ml
>>> import artemis.ml.tools
>>> import artemis.ml.tools.running_averages
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'artemis.ml.tools.running_averages'
```

However, I notice that you wrote:
"(Note, this doesn't work if you have Anaconda installed, as it does not work with the -e option). Use pip install artemis-ml in this case instead."

What should I do?
